routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@homepage')->name('homepage');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/shop', 'HomeController@shop')->name('shop');
Route::get('/produk-detail/{id}', 'HomeController@productDetail')->name('productDetail');
Route::get('/login-register', 'HomeController@userLoginRegister')->name('login-register');
Auth::routes();

Route::get('/admin/logout', function () {
    Auth::logout();
    return redirect('/login');
});


Route::middleware(['auth', 'user'])->group(function () {
    Route::get('/user/dashboard', 'UserController@userDashboard')->name('userDashboard');
    Route::get('/user/transaksi/{id}', 'UserController@userTransaksi')->name('userTransaksi');
    Route::post('/user/transaksi/{id}/change', 'UserController@userTransaksiChange')->name('userTransaksiChange');
    Route::post('/user/transaksi/{id}/rating', 'UserController@userTransaksiRating')->name('userTransaksiRating');
    Route::get('/user/cart', 'CartController@userCart')->name('userCart');
    Route::get('/user/checkout', 'CartController@checkout')->name('checkout');
    Route::post('/user/checkout/save', 'CartController@checkoutSave')->name('checkoutSave');
    Route::resource('/cart', CartController::class);
    Route::resource('/user/user', UserController::class);

});

Route::middleware('auth', 'admin')->group(function () {
    Route::get('/admin/dashboard', 'HomeController@dashboardAdmin')->name('dashboardAdmin');
    Route::resource('/admin/user', UserController::class);
    Route::resource('/admin/produk', ProdukController::class);
    Route::resource('/admin/kategori', KategoriController::class);
    Route::resource('/admin/merk', MerkController::class);
    Route::resource('/admin/transaksi', TransaksiController::class);
    Route::get('/transaksi-export', 'HomeController@exportExcel')->name('transaksi.export');
});

app/Merk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Merk extends Model
{
    public function produks()
    {
        return $this->hasMany(Produk::class);
    }
}

app/Http/Controllers/MerkController.php
<?php

namespace App\Http\Controllers;

use App\Merk;
use Illuminate\Http\Request;

class MerkController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $merk = Merk::all();
        return view('admin.merk.index', compact('merk'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.merk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $merek = new Merk();
        $merek->nama_merk = $request->nama_merk;
        $merekgambar = '';
        if (isset($request->gambar)) {
            $merekgambar = $this->uploadGambar($request->gambar);
        }
        $merek->gambar = $merekgambar;
        $merek->save();

        session()->flash('success', 'Berhasil Menambahkan Data Merek!');

        return redirect('/admin/merk');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Merk  $merk
     * @return \Illuminate\Http\Response
     */
    public function show(Merk $merk)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Merk  $merk
     * @return \Illuminate\Http\Response
     */
    public function edit(Merk $merk)
    {
        return view('admin.merk.edit', compact('merk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Merk  $merk
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Merk $merk)
    {
        $merk->nama_merk = $request->nama_merk;
        if (isset($request->gambar)) {
            $merekgambar = $this->uploadGambar($request->gambar);
            $merk->gambar = $merekgambar;
        }
        $merk->save();

        session()->flash('success', 'Berhasil Menambahkan Data Merek!');

        return redirect('/admin/merk');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Merk  $merk
     * @return \Illuminate\Http\Response
     */
    public function destroy(Merk $merk)
    {
        Merk::destroy($merk->id);
        return response()->json(['message' => 'Data Berhasil Dihapus!']);
    }
}

resources/views/admin/merk/create.blade.php
@extends('layouts.admin.app')

@section('content')

<main id="main-container">
    <!-- Hero -->
    <div class="bg-body-light">
      <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
          <h1 class="flex-grow-1 fs-3 fw-semibold my-2 my-sm-3">Tambah Merek</h1>
        </div>
      </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
      <!-- Dynamic Table Full -->
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _js/pages/be_tables_datatables.js -->
          <form action="/admin/merk" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="namaMerek">Nama Merek</label>
                                        <input type="text" class="form-control mt-1" id="namaMerek" placeholder="Masukkan Nama Merek" name="nama_merk" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                  <div class="form-group">
                                      <label class="form-control-label mb-1" for="gambar">Gambar</label>
                                      <input type="file" class="form-control mt-1" id="gambar" name="gambar" required>
                                  </div>
                              </div>
                          </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="col-lg-12 text-end">
                                <a type="button" href="{{ url('/admin/merk') }}" class="btn btn-secondary">Kembali</a>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
          </form>
        </div>
      </div>
      <!-- END Dynamic Table Full -->
      <!-- Dynamic Table Responsive -->
    </div>
    <!-- END Page Content -->
  </main>

@endsection

resources/views/admin/merk/edit.blade.php
@extends('layouts.admin.app')

@section('content')

<main id="main-container">
    <!-- Hero -->
    <div class="bg-body-light">
      <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
          <h1 class="flex-grow-1 fs-3 fw-semibold my-2 my-sm-3">Edit Kategori</h1>
        </div>
      </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
      <!-- Dynamic Table Full -->
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <form action="{{ route('merk.update', $merk->id) }}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="namaMerk">Nama Merk</label>
                                        <input type="text" class="form-control mt-1" id="namaMerk" placeholder="Masukkan Nama Merk" name="nama_merk" value="{{$merk->nama_merk}}"  required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                  <div class="form-group">
                                      <label class="form-control-label mb-1" for="gambar">Gambar</label>
                                      <input type="file" class="form-control mt-1" id="gambar" placeholder="Masukkan Rating Produk" name="gambar">
                                      <a type="button" class="btn btn-sm btn-warning mt-3" href="{{url('upload/'.$merk->gambar)}}" data-fancybox="images" data-caption="Foto {{$merk->nama_merk}}">Lihat Gambar</a>
                                  </div>
                              </div>
                          </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="col-lg-12 text-end">
                                <a type="button" href="{{ url('/admin/merk') }}" class="btn btn-secondary">Kembali</a>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
          </form>
        </div>
      </div>
      <!-- END Dynamic Table Full -->
      <!-- Dynamic Table Responsive -->
    </div>
    <!-- END Page Content -->
  </main>

@endsection

resources/views/admin/merk/index.blade.php
@extends('layouts.admin.app')

@section('content')

<main id="main-container">
    <!-- Hero -->
    <div class="bg-body-light">
      <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
          <h1 class="flex-grow-1 fs-3 fw-semibold my-2 my-sm-3">Merk</h1>
        </div>
      </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
      <!-- Dynamic Table Full -->
      <div class="block block-rounded">
        <div class="block-header row pt-4">
            <div class="col-lg-6">
                <h3 class="block-title">
                    Data <b>Merk</b>
                </h3>
            </div>
            <div class="col-lg-6 text-end">
                <a type="button" href="{{url('/admin/merk/create')}}" class="btn btn-sm btn-success" > <i class="fa fa-plus"></i> Tambah Merk</a>
            </div>
        </div>
        <div class="block-content block-content-full">
          <table class="table table-bordered table-striped table-vcenter data-table">
            <thead>
              <tr>
                <th class="text-center">Gambar</th>
                <th width=30% >Nama Merk</th>
                <th class="text-center" width=30% >Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($merk as $item)
                <tr>
                    <td class="text-center"><img src="{{url('upload/'.$item->gambar)}}" width="30%" alt=""></td>
                    <td>{{$item->nama_merk}}</td>
                    <td class="text-center">
                        <a type="button" href="{{route('merk.edit', $item->id)}}" class="btn btn-info btn-sm"><i class="fa fa-pen"></i> Edit</a>
                        <button type="button" class="btn btn-sm btn-danger delete-data" data-redirect="merk" data-id="{{ $item->id }}" data-token="{{ csrf_token() }}"><i class="fa fa-trash"></i> Delete</button>
                    </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
      <!-- END Dynamic Table Full -->
    </div>
    <!-- END Page Content -->
  </main>

@endsection