routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@homepage')->name('homepage');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/shop', 'HomeController@shop')->name('shop');
Route::get('/produk-detail/{id}', 'HomeController@productDetail')->name('productDetail');
Route::get('/login-register', 'HomeController@userLoginRegister')->name('login-register');
Auth::routes();

Route::get('/admin/logout', function () {
    Auth::logout();
    return redirect('/login');
});


Route::middleware(['auth', 'user'])->group(function () {
    Route::get('/user/dashboard', 'UserController@userDashboard')->name('userDashboard');
    Route::get('/user/transaksi/{id}', 'UserController@userTransaksi')->name('userTransaksi');
    Route::post('/user/transaksi/{id}/change', 'UserController@userTransaksiChange')->name('userTransaksiChange');
    Route::post('/user/transaksi/{id}/rating', 'UserController@userTransaksiRating')->name('userTransaksiRating');
    Route::get('/user/cart', 'CartController@userCart')->name('userCart');
    Route::get('/user/checkout', 'CartController@checkout')->name('checkout');
    Route::post('/user/checkout/save', 'CartController@checkoutSave')->name('checkoutSave');
    Route::resource('/cart', CartController::class);
    Route::resource('/user/user', UserController::class);

});

Route::middleware('auth', 'admin')->group(function () {
    Route::get('/admin/dashboard', 'HomeController@dashboardAdmin')->name('dashboardAdmin');
    Route::resource('/admin/user', UserController::class);
    Route::resource('/admin/produk', ProdukController::class);
    Route::resource('/admin/kategori', KategoriController::class);
    Route::resource('/admin/merk', MerkController::class);
    Route::resource('/admin/transaksi', TransaksiController::class);
    Route::get('/transaksi-export', 'HomeController@exportExcel')->name('transaksi.export');
});

app/Produk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    public function kategori()
    {
        return $this->belongsTo(Kategori::class);
    }

    public function merk()
    {
        return $this->belongsTo(Merk::class);
    }

    public function transaksi_details()
    {
        return $this->hasMany(TransaksiDetail::class);
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Kategori;
use App\Merk;
use App\Produk;
use Illuminate\Http\Request;

class ProdukController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produk = Produk::all();
        return view('admin.produk.index', compact('produk'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = Kategori::all();
        $merk = Merk::all();
        return view('admin.produk.create', ['kategori' => $kategori, 'merk' => $merk]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $produk = new Produk();
        $produk->nama_produk = $request->nama_produk;
        $produk->deskripsi = $request->deskripsi;
        $produk->harga = $request->harga;
        $produk->stok = $request->stok;
        $gambar_produk = '';
        if (isset($request->gambar)) {
            $gambar_produk = $this->uploadGambar($request->gambar);
        }
        $produk->gambar = $gambar_produk;
        $produk->kategori_id = $request->kategori;
        $produk->merk_id = $request->merk;

        $produk->save();

        session()->flash('success', 'Data Produk Berhasil ditambahkan!');
        return redirect('/admin/produk');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function show(Produk $produk)
    {
        $kategori = Kategori::all();
        $merk = Merk::all();
        return view('admin.produk.show', ['produk' => $produk, 'kategori' => $kategori, 'merk' => $merk]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function edit(Produk $produk)
    {
        $kategori = Kategori::all();
        $merk = Merk::all();
        return view('admin.produk.edit', ['produk' => $produk, 'kategori' => $kategori, 'merk' => $merk]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Produk $produk)
    {
        $produk->nama_produk = $request->nama_produk;
        $produk->deskripsi = $request->deskripsi;
        $produk->harga = $request->harga;
        $produk->stok = $request->stok;
        if (isset($request->gambar)) {
            $gambar_produk = $this->uploadGambar($request->gambar);
            $produk->gambar = $gambar_produk;
        }
        $produk->kategori_id = $request->kategori;
        $produk->merk_id = $request->merk;

        $produk->save();

        session()->flash('success', 'Data Produk Berhasil Diubah!');
        return redirect('/admin/produk');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function destroy(Produk $produk)
    {
        Produk::destroy($produk->id);
        return response()->json(['message' => 'Data Berhasil Dihapus!']);
    }
}

resources/views/admin/produk/create.blade.php
@extends('layouts.admin.app')

@section('content')

<main id="main-container">
    <!-- Hero -->
    <div class="bg-body-light">
      <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
          <h1 class="flex-grow-1 fs-3 fw-semibold my-2 my-sm-3">Tambah Produk</h1>
        </div>
      </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
      <!-- Dynamic Table Full -->
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _js/pages/be_tables_datatables.js -->
          <form action="/admin/produk" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="namaProduk">Nama Produk</label>
                                        <input type="text" class="form-control mt-1" id="namaProduk" placeholder="Masukkan Nama Produk" name="nama_produk" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="kategori">Kategori</label>
                                        <select name="kategori" id="kategori" class="form-control">
                                            <option value="">-Pilih Kategori-</option>
                                            @foreach ($kategori as $k)
                                                <option value="{{$k->id}}">{{$k->nama_kategori}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="merk">Merk</label>
                                        <select name="merk" id="merk" class="form-control">
                                            <option value="">-Pilih Merk-</option>
                                            @foreach ($merk as $m)
                                                <option value="{{$m->id}}">{{$m->nama_merk}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="hargaProduk">Harga</label>
                                        <input type="text" class="form-control mt-1" id="hargaProduk" placeholder="Masukkan Harga Produk" name="harga" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="stokProduk">Stok</label>
                                        <input type="number" class="form-control mt-1" id="stokProduk" placeholder="Masukkan Stok Produk" name="stok" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="deskripsiProduk">Deskripsi</label>
                                        <textarea type="text" cols="10" rows="5" class="form-control mt-1" id="deskripsiProduk" placeholder="Masukkan Deskripsi Produk" name="deskripsi" required></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="gambar">Gambar</label>
                                        <input type="file" class="form-control mt-1" id="gambar" placeholder="Masukkan Rating Produk" name="gambar" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="col-lg-12 text-end">
                                <a type="button" href="{{ url('/admin/produk') }}" class="btn btn-secondary">Kembali</a>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
          </form>
        </div>
      </div>
      <!-- END Dynamic Table Full -->
      <!-- Dynamic Table Responsive -->
    </div>
    <!-- END Page Content -->
  </main>

@endsection

resources/views/admin/produk/edit.blade.php
@extends('layouts.admin.app')

@section('content')

<main id="main-container">
    <!-- Hero -->
    <div class="bg-body-light">
      <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
          <h1 class="flex-grow-1 fs-3 fw-semibold my-2 my-sm-3">Edit Produk</h1>
        </div>
      </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
      <!-- Dynamic Table Full -->
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _js/pages/be_tables_datatables.js -->
          <form action="{{route('produk.update',$produk->id)}}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="namaProduk">Nama Produk</label>
                                        <input type="text" class="form-control mt-1" id="namaProduk" placeholder="Masukkan Nama Produk" name="nama_produk" value="{{$produk->nama_produk}}" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="kategori">Kategori</label>
                                        <select name="kategori" id="kategori" class="form-control">
                                            <option value="">-Pilih Kategori-</option>
                                            @foreach ($kategori as $k)
                                                <option value="{{$k->id}}" {{$produk->kategori_id == $k->id ? 'selected' : ''}} >{{$k->nama_kategori}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="merk">Merk</label>
                                        <select name="merk" id="merk" class="form-control">
                                            <option value="">-Pilih Merk-</option>
                                            @foreach ($merk as $m)
                                                <option value="{{$m->id}}" {{$produk->merk_id == $m->id ? 'selected' : ''}} >{{$m->nama_merk}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="hargaProduk">Harga</label>
                                        <input type="text" class="form-control mt-1" id="hargaProduk" placeholder="Masukkan Harga Produk" name="harga" value="{{$produk->harga}}" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="stokProduk">Stok</label>
                                        <input type="number" class="form-control mt-1" id="stokProduk" placeholder="Masukkan Stok Produk" name="stok" value="{{$produk->stok}}" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="deskripsiProduk">Deskripsi</label>
                                        <textarea type="text" cols="10" rows="5" class="form-control mt-1" id="deskripsiProduk" placeholder="Masukkan Deskripsi Produk" name="deskripsi" required>{{$produk->deskripsi}}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="gambar">Gambar</label>
                                        <input type="file" class="form-control mt-1" id="gambar" placeholder="Masukkan Rating Produk" name="gambar">
                                        <a type="button" class="btn btn-sm btn-warning mt-2" href="{{url('upload/'.$produk->gambar)}}" data-fancybox="images" data-caption="Foto {{$produk->nama_produk}}">Lihat Gambar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="col-lg-12 text-end">
                                <a type="button" href="{{ url('/admin/produk') }}" class="btn btn-secondary">Kembali</a>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
          </form>
        </div>
      </div>
      <!-- END Dynamic Table Full -->
      <!-- Dynamic Table Responsive -->
    </div>
    <!-- END Page Content -->
  </main>

@endsection

resources/views/admin/produk/index.blade.php
@extends('layouts.admin.app')

@section('content')

<main id="main-container">
    <!-- Hero -->
    <div class="bg-body-light">
      <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
          <h1 class="flex-grow-1 fs-3 fw-semibold my-2 my-sm-3">Produk</h1>
        </div>
      </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
      <!-- Dynamic Table Full -->
      <div class="block block-rounded">
        <div class="block-header row pt-4">
            <div class="col-lg-6">
                <h3 class="block-title">
                    Data <b>Produk</b>
                </h3>
            </div>
            <div class="col-lg-6 text-end">
                <a type="button" href="{{url('/admin/produk/create')}}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Tambah Produk</a>
            </div>
        </div>
        <div class="block-content block-content-full">
          <table class="table table-bordered table-striped table-vcenter data-table">
            <thead>
              <tr>
                <th>Gambar</th>
                <th>Nama Produk</th>
                <th>Merek</th>
                <th>Kategori</th>
                <th>Stok</th>
                <th>Harga</th>
                <th width="25%" class="text-center">Action</th>
              </tr>
            </thead>
            <tbody>
            @foreach ($produk as $item)
            <tr>
                <td class="text-center align-items-center" ><img style="max-width: 150px;" src="{{url('upload/'.$item->gambar)}}" alt=""></td>
                <td>{{$item->nama_produk}}</td>
                <td>{{$item->merk->nama_merk}}</td>
                <td>{{$item->kategori->nama_kategori}}</td>
                <td>{{$item->stok}}</td>
                <td>Rp. {{number_format($item->harga, 0, '', '.')}}</td>
                <td class="text-center">
                    <a type="button" href="{{route('produk.show', $item->id)}}" class="btn btn-warning btn-sm"><i class="fa fa-eye"></i> Detail</a>
                    <a type="button" href="{{route('produk.edit', $item->id)}}" class="btn btn-info btn-sm"><i class="fa fa-pen"></i> Edit</a>
                    <button type="button" class="btn btn-sm btn-danger delete-data" data-redirect="produk" data-id="{{ $item->id }}" data-token="{{ csrf_token() }}"><i class="fa fa-trash"></i> Delete</button>
                </td>
            </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
      <!-- END Dynamic Table Full -->
    </div>
    <!-- END Page Content -->
  </main>

@endsection

resources/views/admin/produk/show.blade.php
@extends('layouts.admin.app')

@section('content')

<main id="main-container">
    <!-- Hero -->
    <div class="bg-body-light">
      <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
          <h1 class="flex-grow-1 fs-3 fw-semibold my-2 my-sm-3">Detail Produk</h1>
        </div>
      </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
      <!-- Dynamic Table Full -->
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _js/pages/be_tables_datatables.js -->
          <form action="/produk" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="namaProduk">Nama Produk</label>
                                        <input type="text" class="form-control mt-1" id="namaProduk" placeholder="Masukkan Nama Produk" name="nama_produk" value="{{$produk->nama_produk}}" readonly required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="kategori">Kategori</label>
                                        <input type="text" name="" id="" value="{{$produk->kategori->nama_kategori}}" class="form-control"  readonly  >
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="merk">Merk</label>
                                        <input type="text" name="" id="" value="{{$produk->merk->nama_merk}}" class="form-control"  readonly  >
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="hargaProduk">Harga</label>
                                        <input type="text" class="form-control mt-1" id="hargaProduk" placeholder="Masukkan Harga Produk" name="harga" value="{{$produk->harga}}" readonly required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="stokProduk">Stok</label>
                                        <input type="number" class="form-control mt-1" id="stokProduk" placeholder="Masukkan Stok Produk" name="stok" value="{{$produk->stok}}" readonly required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="rating">Rating</label>
                                        <input type="text" class="form-control mt-1" id="rating" placeholder="Masukkan Rating Produk" name="rating" value="{{$produk->rating}}" readonly required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="deskripsiProduk">Deskripsi</label>
                                        <textarea type="text" cols="10" rows="5" class="form-control mt-1" id="deskripsiProduk" placeholder="Masukkan Deskripsi Produk" name="deskripsi" readonly required>{{$produk->deskripsi}}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-control-label mb-1" for="gambar">Gambar</label>
                                    </div>
                                    <img src="{{url('upload/'.$produk->gambar)}}" width="100px" height="100px"  alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="box">
                        <div class="box-body">
                            <div class="col-lg-12 text-end">
                                <a type="button" href="{{ url('/admin/produk') }}" class="btn btn-secondary">Kembali</a>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
          </form>
        </div>
      </div>
      <!-- END Dynamic Table Full -->
      <!-- Dynamic Table Responsive -->
    </div>
    <!-- END Page Content -->
  </main>

@endsection